version: '3.7'

services:
  db:
    image: postgres:11-alpine
    env_file:
      - dataPlane.env
    ports:
      - "5433:5432"

  backend:
    depends_on:
      - db
      - d-transformer
      - u-transformer
    image: rudderlabs/rudder-server:v0

    entrypoint: sh -c './build/wait-for db:5432 -- rudder-server'

    ports:
      - "8080:8080"
    env_file:
      - dataPlane.env

  d-transformer:
    image: rudderlabs/rudder-dest-transformer:v0
    ports:
      - "9090:9090"
    env_file:
      - dataPlane.env

  u-transformer:
    image: rudderlabs/rudder-user-transformer:v0
    ports:
      - "9292:9292"
    env_file:
      - dataPlane.env

  config-backend:
    image: rudderlabs/rudder-config-backend:v0
    ports:
      - "5000:5000"
    env_file:
      - controlPlane.env
    entrypoint: sh -c './wait-for config-db:5432 -- npm run typeorm migration:run && npm start'
  
  web:
    image: rudderlabs/rudder-webapp:v0
    ports:
      - "3000:3000"
    env_file:
      - controlPlane.env

  config-db:
    image: postgres:11-alpine
    env_file:
      - controlPlane.env
    ports:
      - "5434:5432"
